[build]
command = "npm run build --prefix recipe-manager"
publish = "recipe-manager/.output/public"

[functions]
directory = "recipe-manager/.output/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
